#!/usr/bin/env bun
// Build the theme browser: generate the built-in catalog from themes/, then
// bundle tools/site/browse.ts (engine + shiki + json5) into docs/browse.js.
// The Pages workflow deploys docs/ as-is, so the bundle is committed.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadTheme } from "../../src/load.ts";
import { project } from "../../src/project.ts";
import { slugify } from "../../src/slug.ts";

const ROOT = join(import.meta.dir, "..", "..");
const THEMES = join(ROOT, "themes");
const DEFAULT = "shades-of-purple";
// Full themes are fetched on demand from the repo (raw GitHub allows CORS); only
// the default is embedded so the first paint needs no network.
const THEMES_BASE = "https://raw.githubusercontent.com/eduwass/monotheme/main/themes";

const catalog = readdirSync(THEMES).filter((f) => f.endsWith(".json")).sort().map((f) => {
  const t = loadTheme(join(THEMES, f));
  const p = project(t);
  const slug = f.replace(/\.json$/, "");
  return { slug, name: t.name, type: t.type, bg: p.bg, fg: p.fg, accent: p.accent };
});
const def = loadTheme(join(THEMES, DEFAULT + ".json"));
const defTheme = { name: def.name, type: def.type, colors: def.colors, tokenColors: def.tokenColors };
if (!catalog.some((c) => c.slug === DEFAULT)) throw new Error(`default theme ${DEFAULT} missing`);
if (catalog.some((c) => slugify(c.slug) !== c.slug)) throw new Error("theme filenames must already be slugs");

writeFileSync(join(import.meta.dir, "catalog.gen.ts"),
  `// GENERATED by tools/site/build.ts — do not edit.\n` +
  `export interface CatalogEntry { slug: string; name: string; type: "dark" | "light"; bg: string; fg: string; accent: string }\n` +
  `export const THEMES_BASE = ${JSON.stringify(THEMES_BASE)};\n` +
  `export const CATALOG: CatalogEntry[] = ${JSON.stringify(catalog)};\n` +
  `export const DEFAULT_THEME = { slug: ${JSON.stringify(DEFAULT)}, theme: ${JSON.stringify(defTheme)} };\n`);

const res = await Bun.build({
  entrypoints: [join(import.meta.dir, "browse.ts"), join(import.meta.dir, "home.ts")],
  outdir: join(ROOT, "docs"),
  naming: "[name].js",
  target: "browser",
  minify: true,
  sourcemap: "none",
  // the adapters pull in paths.ts, which resolves ~/.config at import time; a
  // stub `process` keeps that harmless in the browser (nothing there reads it).
  banner: 'var process={env:{},platform:"browser",cwd:function(){return "/"}};',
});
if (!res.success) { for (const l of res.logs) console.error(l); process.exit(1); }
for (const out of res.outputs) console.log(`docs/${out.path.split("/").pop()}  ${(out.size / 1024).toFixed(0)} KB`);
console.log(`(${catalog.length} built-in themes, default ${DEFAULT})`);
