// VSCode theme -> Ghostty theme file (palette 0..15 + bg/fg/cursor/selection).
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toGhostty(theme: VscodeTheme): string {
  const p = project(theme);
  const lines = [
    `# ${theme.name} — generated by theme engine`,
    ...p.ansi.map((hex, i) => `palette = ${i}=${hex}`),
    `background = ${p.bg}`,
    `foreground = ${p.fg}`,
    `cursor-color = ${p.cursor}`,
    `selection-background = ${p.selection}`,
    `selection-foreground = ${p.fg}`,
  ];
  return lines.join("\n") + "\n";
}
