// VSCode theme -> hunk [custom_theme] TOML block (UI). Syntax highlighting is a
// shiki/vscode theme passed via syntax_theme (generated by the shiki adapter).
import type { VscodeTheme } from "../load.ts";
import { pick } from "../load.ts";
import { project, scopeColor } from "../project.ts";

export function toHunkCustomTheme(theme: VscodeTheme): string {
  const p = project(theme);
  const c = theme.colors;
  const t = theme.tokenColors;
  const a = p.ansi;
  const sx = (scopes: string[], fb: string) => {
    for (const s of scopes) { const v = scopeColor(t, s); if (v) return v; }
    return fb;
  };
  const addBg = pick(c, ["diffEditor.insertedLineBackground"]) ?? "#263445";
  const delBg = pick(c, ["diffEditor.removedLineBackground"]) ?? "#3E233C";

  return `[custom_theme]
base = "catppuccin-mocha"
label = "${theme.name}"
syntax_theme = "dotfiles.json"
background = "${p.bg}"
panel = "${p.bgPanel}"
panelAlt = "${p.bgPanel}"
border = "${p.fgMuted}"
accent = "${p.accent}"
accentMuted = "${p.border}"
text = "${p.fg}"
muted = "${p.fgMuted}"
addedBg = "${addBg}"
removedBg = "${delBg}"
contextBg = "${p.bgPanel}"
addedContentBg = "${addBg}"
removedContentBg = "${delBg}"
contextContentBg = "${p.bg}"
addedSignColor = "${p.success}"
removedSignColor = "${p.error}"
lineNumberBg = "${p.bgPanel}"
lineNumberFg = "${p.fgMuted}"
selectedHunk = "${p.border}"
badgeAdded = "${p.success}"
badgeRemoved = "${p.error}"
badgeNeutral = "${p.fgMuted}"
fileNew = "${p.success}"
fileDeleted = "${p.error}"
fileRenamed = "${p.accent}"
fileModified = "${a[5]}"
fileUntracked = "${a[6]}"
noteBorder = "${a[5]}"
noteBackground = "${p.bgPanel}"
noteTitleBackground = "${p.border}"
noteTitleText = "${p.fg}"

[custom_theme.syntax]
default = "${p.fg}"
keyword = "${sx(["keyword", "storage.type"], a[3]!)}"
string = "${sx(["string"], a[2]!)}"
comment = "${sx(["comment"], a[5]!)}"
number = "${sx(["constant.numeric"], a[1]!)}"
function = "${sx(["entity.name.function"], p.accent)}"
property = "${sx(["variable.other.property", "support.type.property-name"], a[3]!)}"
type = "${sx(["entity.name.type", "support.type"], a[6]!)}"
punctuation = "${sx(["punctuation"], p.fg)}"
`;
}
