// VSCode theme -> a complete nvim colorscheme (colors/dotfiles.lua). Mirrors the
// user's hand-tuned override structure (editor, syntax, treesitter, plugin groups)
// but derives every color from the active theme, so nvim follows theme switches.
import type { VscodeTheme } from "../load.ts";
import { mix } from "../load.ts";
import { project, scopeColor } from "../project.ts";

export function toNvim(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  const t = theme.tokenColors;
  const sx = (scopes: string[], fb: string) => {
    for (const s of scopes) { const v = scopeColor(t, s); if (v) return v; }
    return fb;
  };
  // palette derived from the theme (matches the user's ~15-color SoP palette roles)
  const c = {
    bg: p.bg,
    panel: mix(p.bg, "#000000", 0.22),     // floats / sidebars / statusline
    cursorLine: mix(p.bg, "#000000", 0.12),
    fg: p.fg,
    muted: p.fgMuted,
    lineNr: mix(p.bg, p.fgMuted, 0.42),
    indent: mix(p.bg, p.fgMuted, 0.28),
    visual: p.selection,
    accent: p.accent,
    comment: sx(["comment"], a[5]!),
    string: sx(["string"], a[2]!),
    number: sx(["constant.numeric"], a[1]!),
    keyword: sx(["keyword", "storage.type"], a[3]!),
    func: sx(["entity.name.function"], p.accent),
    type: sx(["entity.name.type", "support.type"], p.fgMuted),
    cyan: sx(["variable.other.property", "support.type.property-name"], a[6]!),
    tag: sx(["entity.name.tag"], a[6]!),
    error: p.error,
    warn: p.warning,
    info: a[6]!,
    hint: p.fgMuted,
    add: p.success,
    change: p.accent,
    del: p.error,
  };
  const hl = (group: string, opts: Record<string, string | boolean>) => {
    const parts = Object.entries(opts).map(([k, v]) => `${k} = ${typeof v === "string" ? `"${v}"` : v}`);
    return `  hl("${group}", { ${parts.join(", ")} })`;
  };
  const term = a.map((hex, i) => `vim.g.terminal_color_${i} = "${hex}"`).join("\n");

  return `-- ${theme.name} — generated by theme engine. Do not edit; run \`theme set <name>\`.
vim.o.background = "${theme.type}"
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "dotfiles"
${term}

local hl = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

-- Editor
${hl("Normal", { bg: c.bg, fg: c.fg })}
${hl("NormalNC", { bg: c.bg, fg: c.fg })}
${hl("NormalFloat", { bg: c.panel, fg: c.fg })}
${hl("FloatBorder", { bg: c.panel, fg: c.muted })}
${hl("SignColumn", { bg: c.bg })}
${hl("EndOfBuffer", { bg: c.bg, fg: c.bg })}
${hl("MsgArea", { bg: c.bg })}
${hl("CursorLine", { bg: c.cursorLine })}
${hl("CursorLineNr", { fg: c.accent, bold: true, bg: c.cursorLine })}
${hl("LineNr", { fg: c.lineNr, bg: c.bg })}
${hl("Visual", { bg: c.visual })}
${hl("ColorColumn", { bg: c.cursorLine })}
${hl("WinSeparator", { fg: c.panel, bg: c.bg })}
${hl("VertSplit", { fg: c.panel, bg: c.bg })}

-- Syntax
${hl("Comment", { fg: c.comment, italic: true })}
${hl("String", { fg: c.string })}
${hl("Character", { fg: c.string })}
${hl("Number", { fg: c.number })}
${hl("Float", { fg: c.number })}
${hl("Boolean", { fg: c.number })}
${hl("Keyword", { fg: c.keyword, italic: true })}
${hl("Statement", { fg: c.keyword })}
${hl("Conditional", { fg: c.keyword, italic: true })}
${hl("Repeat", { fg: c.keyword, italic: true })}
${hl("Function", { fg: c.func })}
${hl("Identifier", { fg: c.fg })}
${hl("Type", { fg: c.type })}
${hl("Constant", { fg: c.number })}
${hl("Operator", { fg: c.keyword })}
${hl("PreProc", { fg: c.keyword })}
${hl("Special", { fg: c.keyword })}
${hl("Delimiter", { fg: c.fg })}

-- Treesitter
${hl("@comment", { link: "Comment" })}
${hl("@string", { fg: c.string })}
${hl("@number", { fg: c.number })}
${hl("@boolean", { fg: c.number })}
${hl("@function", { fg: c.func })}
${hl("@function.call", { fg: c.func })}
${hl("@function.builtin", { fg: c.func })}
${hl("@method", { fg: c.func })}
${hl("@keyword", { fg: c.keyword, italic: true })}
${hl("@keyword.return", { fg: c.keyword, italic: true })}
${hl("@keyword.function", { fg: c.keyword, italic: true })}
${hl("@keyword.operator", { fg: c.keyword })}
${hl("@keyword.import", { fg: c.keyword, italic: true })}
${hl("@conditional", { fg: c.keyword, italic: true })}
${hl("@variable", { fg: c.fg })}
${hl("@variable.builtin", { fg: c.cyan, italic: true })}
${hl("@variable.parameter", { fg: c.fg })}
${hl("@property", { fg: c.cyan })}
${hl("@field", { fg: c.cyan })}
${hl("@type", { fg: c.type })}
${hl("@type.builtin", { fg: c.type, italic: true })}
${hl("@constructor", { fg: c.type })}
${hl("@constant", { fg: c.number })}
${hl("@constant.builtin", { fg: c.number })}
${hl("@operator", { fg: c.keyword })}
${hl("@punctuation", { fg: c.fg })}
${hl("@punctuation.bracket", { fg: c.fg })}
${hl("@punctuation.delimiter", { fg: c.fg })}
${hl("@tag", { fg: c.tag })}
${hl("@tag.attribute", { fg: c.accent, italic: true })}
${hl("@tag.delimiter", { fg: c.fg })}

-- UI
${hl("Pmenu", { bg: c.panel, fg: c.muted })}
${hl("PmenuSel", { bg: c.visual, fg: c.fg })}
${hl("PmenuThumb", { bg: c.muted })}
${hl("StatusLine", { bg: c.panel, fg: c.muted })}
${hl("StatusLineNC", { bg: c.panel, fg: c.lineNr })}
${hl("TabLineSel", { bg: c.bg, fg: c.fg })}
${hl("Search", { bg: c.accent, fg: c.panel })}
${hl("IncSearch", { bg: c.keyword, fg: c.panel })}
${hl("CurSearch", { bg: c.number, fg: c.panel })}
${hl("DiagnosticError", { fg: c.error })}
${hl("DiagnosticWarn", { fg: c.warn })}
${hl("DiagnosticInfo", { fg: c.info })}
${hl("DiagnosticHint", { fg: c.hint })}
${hl("GitSignsAdd", { fg: c.add, bg: c.bg })}
${hl("GitSignsChange", { fg: c.change, bg: c.bg })}
${hl("GitSignsDelete", { fg: c.del, bg: c.bg })}
${hl("IblIndent", { fg: c.indent })}
${hl("IblScope", { fg: c.muted })}

-- Neo-tree
${hl("NeoTreeNormal", { bg: c.bg, fg: c.muted })}
${hl("NeoTreeNormalNC", { bg: c.bg, fg: c.muted })}
${hl("NeoTreeDirectoryName", { fg: c.muted, bold: true })}
${hl("NeoTreeFileName", { fg: c.fg })}
${hl("NeoTreeGitModified", { fg: c.change })}
${hl("NeoTreeGitAdded", { fg: c.add })}
${hl("NeoTreeGitDeleted", { fg: c.del })}
${hl("NeoTreeIndentMarker", { fg: c.indent })}
${hl("NeoTreeCursorLine", { bg: c.cursorLine })}

-- Telescope
${hl("TelescopeNormal", { bg: c.panel, fg: c.fg })}
${hl("TelescopeBorder", { bg: c.panel, fg: c.indent })}
${hl("TelescopePromptTitle", { bg: c.keyword, fg: c.panel, bold: true })}
${hl("TelescopePreviewTitle", { bg: c.add, fg: c.panel, bold: true })}
${hl("TelescopeResultsTitle", { bg: c.muted, fg: c.panel, bold: true })}
${hl("TelescopeSelection", { bg: c.visual, fg: c.fg })}
${hl("TelescopeMatching", { fg: c.accent, bold: true })}

-- Which-key
${hl("WhichKey", { fg: c.accent })}
${hl("WhichKeyGroup", { fg: c.keyword })}
${hl("WhichKeyDesc", { fg: c.muted })}
${hl("WhichKeyFloat", { bg: c.panel })}
`;
}
