// VSCode theme -> tmux @color-* user vars. The user's tmux.conf references
// #{@color-accent} etc.; we just (re)define them, then `tmux source-file`.
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toTmux(theme: VscodeTheme): string {
  const p = project(theme);
  return [
    `# ${theme.name} — generated by theme engine`,
    `set -g @color-accent "${p.accent}"`,
    `set -g @color-fg "${p.fgMuted}"`,
    `set -g @color-fg-dim "${p.fgMuted}80"`, // tmux supports #rrggbbaa
    `set -g @color-fg-hint "${p.fgMuted}50"`,
    `set -g @color-border "${p.border}"`,
    `set -g @color-border-active "${p.borderActive}"`,
  ].join("\n") + "\n";
}
