// VSCode theme -> yazi flavor.toml (UI). Syntax preview is the tmtheme.xml,
// generated separately via the shared tmTheme adapter.
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toYaziFlavor(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  const on = (fg: string, bg: string, extra = "") => `{ fg = "${fg}", bg = "${bg}"${extra} }`;
  return `# ${theme.name} — generated by theme engine

[mgr]
cwd = { fg = "${a[6]}" }
hovered         = ${on(p.bg, p.accent, ", bold = true")}
preview_hovered = { underline = true }
find_keyword  = { fg = "${p.accent}", italic = true }
find_position = { fg = "${a[5]}", bg = "reset", italic = true }
marker_copied   = { fg = "${p.success}", bg = "${p.success}" }
marker_cut      = { fg = "${p.error}", bg = "${p.error}" }
marker_marked   = { fg = "${a[6]}", bg = "${a[6]}" }
marker_selected = { fg = "${a[5]}", bg = "${a[5]}" }
count_copied   = ${on(p.bg, p.success)}
count_cut      = ${on(p.fg, p.error)}
count_selected = ${on(p.bg, p.accent)}
border_symbol = "│"
border_style  = { fg = "${p.border}" }

[tabs]
active   = ${on(p.bg, p.accent, ", bold = true")}
inactive = ${on(p.fgMuted, p.bgPanel)}

[mode]
normal_main = ${on(p.bg, p.accent, ", bold = true")}
normal_alt  = ${on(p.accent, p.bgPanel)}
select_main = ${on(p.bg, p.success, ", bold = true")}
select_alt  = ${on(p.success, p.bgPanel)}
unset_main  = ${on(p.bg, p.error, ", bold = true")}
unset_alt   = ${on(p.error, p.bgPanel)}

[status]
overall   = { fg = "${p.fg}" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[pick]
border   = { fg = "${p.accent}" }
active   = { fg = "${a[5]}", bold = true }
inactive = { fg = "${p.fgMuted}" }

[input]
border   = { fg = "${p.accent}" }
title    = { fg = "${p.fg}" }
value    = { fg = "${p.fg}" }
selected = { bg = "${p.selection}" }

[cmp]
border         = { fg = "${p.accent}" }
active         = ${on(p.bg, p.accent)}
inactive       = { fg = "${p.fgMuted}" }

[tasks]
border  = { fg = "${p.accent}" }
title   = { fg = "${p.fg}" }
hovered = { fg = "${a[5]}", underline = true }

[which]
cols            = 3
mask            = { bg = "${p.bgPanel}" }
cand            = { fg = "${a[6]}" }
rest            = { fg = "${p.fgMuted}" }
desc            = { fg = "${p.fg}" }
separator       = "  "
separator_style = { fg = "${p.border}" }

[help]
on      = { fg = "${p.accent}" }
run     = { fg = "${a[5]}" }
hovered = ${on(p.fg, p.selection, ", bold = true")}
footer  = ${on(p.fgMuted, p.bgPanel)}
`;
}
