// ┌─────────────────────────────────────────────────────────────────────────┐
// │  Add a tool in ONE file.  Copy me to src/targets/<yourtool>.ts, fill in   │
// │  the blanks, delete what you don't use. It's auto-discovered — no list to  │
// │  edit anywhere.  Full guide + the `c` (context) reference: docs/ADAPTERS.md │
// └─────────────────────────────────────────────────────────────────────────┘
import { defineTarget } from "../target-kit.ts";
import { project } from "../project.ts";
import type { VscodeTheme } from "../load.ts";

// 1) Your format function: turn a theme into your tool's config text.
//    `project(theme)` gives the palette: bg, fg, ansi[0..15], accent, selection, …
function toYourtool(theme: VscodeTheme): string {
  const p = project(theme);
  return [
    `# generated by monotheme`,
    `background ${p.bg}`,
    `foreground ${p.fg}`,
    ...p.ansi.map((hex, i) => `color${i} ${hex}`),
  ].join("\n") + "\n";
}

// 2) The target: how/where to apply it. Pick the SIMPLE shape (below) or, for
//    anything fancier, swap `file`/`render`/`reload` for a single `build`.
export default defineTarget({
  name: "yourtool",

  // optional: only run when the tool is actually installed
  detect: (c) => c.has(c.config("yourtool")),

  // where to write — ALWAYS use the OS-aware helpers, never a hardcoded path:
  //   c.config(...)  → ~/.config/… (linux/mac) · %APPDATA%\… (win)
  //   c.appSupport(...) → ~/Library/Application Support/… on mac, else ~/.config
  //   c.home(...) → ~/…
  file: (c) => c.config("yourtool", "monotheme.conf"),

  // what to write:
  render: (c) => toYourtool(c.theme),

  // optional: a shell command to live-reload the running app. Errors are swallowed,
  // so an app that isn't running is automatically a no-op — no need for `|| true`.
  // Branch on the OS when reload differs per platform:
  reload: (c) => (c.mac ? `osascript -e '…'` : "pkill -USR1 -x yourtool"),
});

// ── Need more than one file, or custom logic? Use `build` instead of file/render:
//
// export default defineTarget({
//   name: "yourtool",
//   detect: (c) => c.has(c.config("yourtool")),
//   build: (c) => {
//     c.write(c.config("yourtool", "theme.json"), toYourtool(c.theme));
//     c.setJson(c.config("yourtool", "settings.json"), "theme", "monotheme"); // patch one JSON key
//     c.run("yourtool reload");                                              // run a reload cmd
//     return "theme.json (live-reload)"; // short status shown in `theme set` output
//   },
// });
