import { defineTarget } from "../target-kit.ts";
// VSCode theme -> Alacritty colors (TOML). Written to a stable slot the user
// imports once (`general.import`); Alacritty's live_config_reload picks up changes.
// Key layout mirrors the widely-used omarchy alacritty template.
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toAlacritty(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  return `# ${theme.name} — generated by monotheme
[colors.primary]
background = "${p.bg}"
foreground = "${p.fg}"

[colors.cursor]
text = "${p.bg}"
cursor = "${p.cursor}"

[colors.vi_mode_cursor]
text = "${p.bg}"
cursor = "${p.cursor}"

[colors.selection]
text = "${p.fg}"
background = "${p.selection}"

[colors.normal]
black = "${a[0]}"
red = "${a[1]}"
green = "${a[2]}"
yellow = "${a[3]}"
blue = "${a[4]}"
magenta = "${a[5]}"
cyan = "${a[6]}"
white = "${a[7]}"

[colors.bright]
black = "${a[8]}"
red = "${a[9]}"
green = "${a[10]}"
yellow = "${a[11]}"
blue = "${a[12]}"
magenta = "${a[13]}"
cyan = "${a[14]}"
white = "${a[15]}"
`;
}

export default defineTarget({
  name: "alacritty",
  detect: (c) => c.has(c.config("alacritty")),
  // Add `general.import = ["~/.config/alacritty/monotheme.toml"]` once; live_config_reload
  // re-reads on change, and touching the main config nudges it.
  file: (c) => c.config("alacritty", "monotheme.toml"),
  render: (c) => toAlacritty(c.theme),
  reload: (c) => `touch "${c.config("alacritty", "alacritty.toml")}"`,
});
