import { defineTarget } from "../target-kit.ts";
// VSCode theme -> btop .theme file (42 keys: base UI + 3-stop gradients).
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toBtop(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  const grad = (k: string, s: string, m: string, e: string) =>
    [`theme[${k}_start]="${s}"`, `theme[${k}_mid]="${m}"`, `theme[${k}_end]="${e}"`];
  const kv = (k: string, v: string) => `theme[${k}]="${v}"`;

  const lines = [
    `# ${theme.name} — generated by theme engine`,
    kv("main_bg", p.bg),
    kv("main_fg", p.fg),
    kv("title", p.fg),
    kv("hi_fg", p.accent),
    kv("selected_bg", p.selection),
    kv("selected_fg", p.fg),
    kv("inactive_fg", p.fgMuted),
    kv("graph_text", p.fgMuted),
    kv("meter_bg", p.border),
    kv("proc_misc", p.accent),
    kv("cpu_box", p.border),
    kv("mem_box", p.border),
    kv("net_box", p.border),
    kv("proc_box", p.border),
    kv("div_line", p.border),
    // gradients: low -> mid -> high (green/cyan/blue for "good", green->yellow->red for load)
    ...grad("temp", a[2]!, a[3]!, a[1]!),
    ...grad("cpu", a[2]!, a[3]!, a[1]!),
    ...grad("free", a[2]!, a[2]!, a[10]!),
    ...grad("cached", a[6]!, a[4]!, a[12]!),
    ...grad("available", a[6]!, a[6]!, a[14]!),
    ...grad("used", a[2]!, a[3]!, a[1]!),
    ...grad("download", a[2]!, a[6]!, a[4]!),
    ...grad("upload", a[3]!, a[5]!, a[1]!),
    ...grad("process", a[2]!, a[3]!, a[1]!),
  ];
  return lines.join("\n") + "\n";
}

export default defineTarget({
  name: "btop",
  // btop.conf pins color_theme = "monotheme"; we overwrite that slot. SIGUSR2 reloads.
  file: (c) => c.config("btop", "themes", "monotheme.theme"),
  render: (c) => toBtop(c.theme),
  reload: () => "pkill -USR2 -x btop",
});
