import { defineTarget } from "../target-kit.ts";
// base16 scheme -> fzf --color opts (sourced as FZF_DEFAULT_OPTS). Proof that any
// base16-templated tool can be driven from our projected scheme.
import type { VscodeTheme } from "../load.ts";
import { toBase16 } from "../base16.ts";

export function toFzf(theme: VscodeTheme): string {
  const b = toBase16(theme);
  const color = [
    // bg/bg+/gutter transparent (-1 = terminal default) — fzf then always matches
    // whatever the terminal is actually showing, so a theme switch in an already-
    // open shell never leaves stale fzf colors behind, even before a reload.
    `bg:-1`, `bg+:-1`, `fg:${b.base05}`, `fg+:${b.base06}`,
    `hl:${b.base0D}`, `hl+:${b.base0D}`, `header:${b.base0E}`, `info:${b.base0A}`,
    `marker:${b.base0B}`, `pointer:${b.base08}`, `prompt:${b.base0E}`,
    `spinner:${b.base0C}`, `border:${b.base02}`, `gutter:-1`,
  ].join(",");
  return `# ${theme.name} — generated by theme engine (base16 bridge)
export FZF_DEFAULT_OPTS="\${FZF_DEFAULT_OPTS:-} --color=${color}"
`;
}

export default defineTarget({
  name: "fzf",
  detect: (c) => c.hasCmd("fzf"),
  // sourced from your shell rc as FZF_DEFAULT_OPTS; next shell/fzf picks it up.
  file: (c) => c.config("fzf", "theme.sh"),
  render: (c) => toFzf(c.theme),
});
