import { defineTarget } from "../target-kit.ts";
// Ghostty fonts (opt-in, terminal role). Ghostty *theme* files (loaded via
// `theme = monotheme`) are restricted to colour keys and ignore font-family, so
// fonts can't ride the colour slot. We write a dedicated include file AND auto-wire
// it into the main config (`config-file = monotheme-fonts`, placed last so it wins
// over any font-family the user set earlier). Only runs when a terminal font is set.

export default defineTarget({
  name: "ghostty-font",
  detect: (c) => {
    const f = c.font("terminal");
    return (!!f.family || f.size != null) && c.has(c.config("ghostty", "config"));
  },
  build: (c) => {
    const f = c.font("terminal");
    const include = c.config("ghostty", "monotheme-fonts");
    const lines = ["# fonts — generated by monotheme (auto-included from your ghostty config)"];
    // Ghostty's font-family is ADDITIVE — repeating appends a fallback rather than
    // replacing. An empty value resets the list, so we clear first, then set ours as
    // the sole primary; otherwise a font-family set elsewhere would win.
    if (f.family) lines.push("font-family = ", `font-family = ${f.family}`);
    if (f.size != null) lines.push(`font-size = ${f.size}`);
    c.write(include, lines.join("\n") + "\n");

    // Auto-wire the include into the main config (once), LAST so it overrides any
    // earlier font-family. Without this the file is written but never loaded — the
    // #1 "ghostty didn't pick up my font" gotcha.
    const cfgPath = c.config("ghostty", "config");
    const cfg = c.read(cfgPath);
    let wired = "include already wired";
    if (!/^[ \t]*config-file[ \t]*=[ \t]*monotheme-fonts[ \t]*$/m.test(cfg)) {
      const sep = cfg === "" || cfg.endsWith("\n") ? "" : "\n";
      c.write(cfgPath, `${cfg}${sep}\n# monotheme: terminal font (kept last so it overrides)\nconfig-file = monotheme-fonts\n`);
      wired = "wired config-file into ghostty config";
    }

    c.run(c.mac ? `osascript -e 'tell application "Ghostty" to perform action "reload_config" on terminal 1'` : "pkill -USR2 -x ghostty");
    return `ghostty-font → ${f.family ?? "size only"} (${wired})`;
  },
});
