import { defineTarget } from "../target-kit.ts";
// Ghostty fonts (opt-in, terminal role). Ghostty *theme* files (loaded via
// `theme = monotheme`) are restricted to colour keys and ignore font-family, so
// fonts can't ride the colour slot. Instead we write a dedicated include file and
// the user points at it once from their main config:
//
//   config-file = monotheme-fonts
//
// Only writes when a terminal font is configured, so absent fonts.json = no-op.

export default defineTarget({
  name: "ghostty-font",
  detect: (c) => {
    const f = c.font("terminal");
    return (!!f.family || f.size != null) && c.has(c.config("ghostty", "config"));
  },
  file: (c) => c.config("ghostty", "monotheme-fonts"),
  render: (c) => {
    const f = c.font("terminal");
    const lines = ["# fonts — generated by monotheme (add `config-file = monotheme-fonts` to your ghostty config)"];
    if (f.family) lines.push(`font-family = ${f.family}`);
    if (f.size != null) lines.push(`font-size = ${f.size}`);
    return lines.join("\n") + "\n";
  },
  // reuse ghostty's reload path.
  reload: (c) =>
    c.mac
      ? `osascript -e 'tell application "Ghostty" to perform action "reload_config" on terminal 1'`
      : "pkill -USR2 -x ghostty",
});
