import { defineTarget } from "../target-kit.ts";
// VSCode theme -> Kitty colors (conf). Written to a stable slot the user includes
// once (`include monotheme.conf`); `kill -SIGUSR1 kitty` live-reloads it.
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toKitty(theme: VscodeTheme): string {
  const p = project(theme);
  const lines = [
    `# ${theme.name} — generated by monotheme`,
    `background ${p.bg}`,
    `foreground ${p.fg}`,
    `cursor ${p.cursor}`,
    `cursor_text_color ${p.bg}`,
    `selection_background ${p.selection}`,
    `selection_foreground ${p.fg}`,
    ...p.ansi.map((hex, i) => `color${i} ${hex}`),
  ];
  return lines.join("\n") + "\n";
}

export default defineTarget({
  name: "kitty",
  detect: (c) => c.has(c.config("kitty", "kitty.conf")),
  // Add `include monotheme.conf` to kitty.conf once; SIGUSR1 live-reloads colors.
  // The same included file also carries the terminal font (opt-in).
  file: (c) => c.config("kitty", "monotheme.conf"),
  render: (c) => {
    const f = c.font("terminal");
    let out = toKitty(c.theme);
    if (f.family) out += `font_family ${f.family}\n`;
    if (f.size != null) out += `font_size ${f.size}\n`;
    return out;
  },
  reload: () => "pkill -USR1 -x kitty",
});
