import { defineTarget } from "../target-kit.ts";
// VSCode theme -> Omarchy v4 theme (colors.toml). Omarchy regenerates configs for
// hyprland, the Quickshell bar, chromium, the lock screen etc. from this palette,
// so this one file reskins the whole desktop. Key set mirrors the shipped themes
// (e.g. /usr/share/omarchy/themes/tokyo-night/colors.toml). Backgrounds are
// intentionally omitted: omarchy-theme-set applies colors without one, and user
// wallpapers live in ~/.config/omarchy/backgrounds/<theme>/ independently.
import type { VscodeTheme } from "../load.ts";
import { stripAlpha } from "../load.ts";
import { project } from "../project.ts";

// Blend hex `a` toward hex `b` by t (0..1). Both #rrggbb.
function blend(a: string, b: string, t: number): string {
  const ch = (h: string, i: number) => parseInt(h.slice(i, i + 2), 16);
  const mix = (i: number) => Math.round(ch(a, i) + (ch(b, i) - ch(a, i)) * t);
  return "#" + [1, 3, 5].map((i) => mix(i).toString(16).padStart(2, "0")).join("");
}
const darken = (hex: string, t: number) => blend(hex, "#000000", t);
const lighten = (hex: string, t: number) => blend(hex, "#ffffff", t);

export function toOmarchy(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi.map((x) => stripAlpha(x));
  const bg = stripAlpha(p.bg);
  const fg = stripAlpha(p.fg);
  const orange = blend(a[1]!, a[3]!, 0.5);
  const kv = (k: string, v: string) => `${k} = "${v}"`;

  const lines = [
    `# ${theme.name} — generated by monotheme`,
    kv("mode", theme.type === "light" ? "light" : "dark"),
    "",
    kv("accent", stripAlpha(p.accent)),
    kv("selection", stripAlpha(p.selection)),
    kv("muted", stripAlpha(p.fgMuted)),
    "",
    kv("background", bg),
    kv("dark_background", darken(bg, 0.25)),
    kv("darker_background", darken(bg, 0.45)),
    kv("lighter_background", stripAlpha(p.bgPanel) !== bg ? stripAlpha(p.bgPanel) : lighten(bg, 0.08)),
    "",
    kv("foreground", fg),
    kv("dark_foreground", stripAlpha(p.fgMuted)),
    kv("light_foreground", lighten(fg, 0.25)),
    kv("bright_foreground", a[15]!),
    "",
    kv("red", a[1]!),
    kv("yellow", a[3]!),
    kv("orange", orange),
    kv("green", a[2]!),
    kv("cyan", a[6]!),
    kv("blue", a[4]!),
    kv("magenta", a[5]!),
    kv("brown", darken(orange, 0.35)),
    "",
    kv("bright_red", a[9]!),
    kv("bright_yellow", a[11]!),
    kv("bright_green", a[10]!),
    kv("bright_cyan", a[14]!),
    kv("bright_blue", a[12]!),
    kv("bright_magenta", a[13]!),
  ];
  return lines.join("\n") + "\n";
}

// Omarchy's theme switch also re-themes VS Code/Cursor/VSCodium with its lossy
// 16-color projection, overwriting monotheme's full-fidelity editor themes. It
// ships first-party opt-outs for exactly this (omarchy-toggle-enabled reads
// marker files): setting them makes omarchy-theme-set-vscode leave editors to
// their owner. Zed and nvim need no toggle — Omarchy only themes its own nvim
// distro, and Zed only via the opt-in omazed tool.
const EDITOR_SKIP_TOGGLES = [
  "skip-vscode-theme-changes",
  "skip-vscode-insiders-theme-changes",
  "skip-codium-theme-changes",
  "skip-cursor-theme-changes",
];

export default defineTarget({
  name: "omarchy",
  // Only Omarchy boxes have the theme-set CLI; everywhere else this no-ops.
  detect: (c) => c.hasCmd("omarchy-theme-set"),
  build: (c) => {
    c.write(c.config("omarchy", "themes", c.slot, "colors.toml"), toOmarchy(c.theme));
    for (const t of EDITOR_SKIP_TOGGLES)
      c.write(c.home(".local", "state", "omarchy", "toggles", t), "");
    // Full desktop reskin (bar, hyprland, lock screen, …) from the slot theme.
    c.run(`omarchy-theme-set ${c.slot}`);
    return `themes/${c.slot}/colors.toml (desktop reskin; editors left to monotheme)`;
  },
});
