import { defineTarget } from "../target-kit.ts";
// VSCode theme -> Warp theme (YAML) in ~/.warp/themes/. Warp hot-reloads theme
// files in that dir; the user selects "monotheme" once in Settings > Appearance.
// `details` tells Warp whether the background is dark or light.
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toWarp(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  return `# ${theme.name} — generated by monotheme
accent: "${p.accent}"
background: "${p.bg}"
foreground: "${p.fg}"
details: "${theme.type === "light" ? "lighter" : "darker"}"
terminal_colors:
  normal:
    black: "${a[0]}"
    red: "${a[1]}"
    green: "${a[2]}"
    yellow: "${a[3]}"
    blue: "${a[4]}"
    magenta: "${a[5]}"
    cyan: "${a[6]}"
    white: "${a[7]}"
  bright:
    black: "${a[8]}"
    red: "${a[9]}"
    green: "${a[10]}"
    yellow: "${a[11]}"
    blue: "${a[12]}"
    magenta: "${a[13]}"
    cyan: "${a[14]}"
    white: "${a[15]}"
`;
}

export default defineTarget({
  name: "warp",
  detect: (c) => c.has(c.home(".warp")),
  // Warp hot-reloads theme files in ~/.warp/themes/; select "monotheme" once in
  // Settings > Appearance > Themes (Warp has no CLI to switch the active theme).
  file: (c) => c.home(".warp", "themes", "monotheme.yaml"),
  render: (c) => toWarp(c.theme),
});
