import { defineTarget } from "../target-kit.ts";
// VSCode theme -> WezTerm color scheme (TOML). Dropped into wezterm's auto-scanned
// colors/ dir; the user sets `config.color_scheme = "monotheme"` once. ansi/brights
// are 8-element arrays (normal 0-7, bright 8-15).
import type { VscodeTheme } from "../load.ts";
import { project } from "../project.ts";

export function toWezterm(theme: VscodeTheme): string {
  const p = project(theme);
  const a = p.ansi;
  const arr = (xs: string[]) => xs.map((h) => `"${h}"`).join(", ");
  return `# ${theme.name} — generated by monotheme
[colors]
foreground = "${p.fg}"
background = "${p.bg}"
cursor_bg = "${p.cursor}"
cursor_fg = "${p.bg}"
cursor_border = "${p.cursor}"
selection_bg = "${p.selection}"
selection_fg = "${p.fg}"
ansi = [${arr(a.slice(0, 8))}]
brights = [${arr(a.slice(8, 16))}]
`;
}

export default defineTarget({
  name: "wezterm",
  detect: (c) => c.has(c.config("wezterm")) || c.has(c.home(".wezterm.lua")),
  // Auto-scanned colors/ dir; set `config.color_scheme = "monotheme"` once. Touch the
  // lua config (if present) so wezterm's auto-reload re-reads the scheme.
  file: (c) => c.config("wezterm", "colors", "monotheme.toml"),
  render: (c) => toWezterm(c.theme),
  reload: (c) =>
    `for f in "${c.config("wezterm", "wezterm.lua")}" "${c.home(".wezterm.lua")}"; do [ -f "$f" ] && touch "$f"; done; true`,
});
