#!/usr/bin/env bun
// Codegen: bundle the default theme library into a single TS module so a
// `bun build --compile` binary carries its themes (there's no themes/ dir on
// disk next to a standalone binary). Run before building the binary:
//   bun scripts/embed-themes.ts && bun build --compile ...
// Regenerate whenever themes/ changes. The generated file is committed so the
// binary build is reproducible.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import JSON5 from "json5";

const REPO = resolve(dirname(new URL(import.meta.url).pathname), "..");
const THEMES = join(REPO, "themes");
const OUT = join(REPO, "src", "embedded-themes.gen.ts");

const entries: string[] = [];
for (const f of readdirSync(THEMES).sort()) {
  if (!f.endsWith(".json")) continue;
  const slug = f.replace(/\.json$/, "");
  const raw = JSON5.parse(readFileSync(join(THEMES, f), "utf8"));
  // keep only the canonical fields; minified to keep the module compact.
  const min = JSON.stringify({ name: raw.name, type: raw.type ?? "dark", colors: raw.colors, tokenColors: raw.tokenColors });
  entries.push(`  ${JSON.stringify(slug)}: ${min},`);
}

const header = `// GENERATED by scripts/embed-themes.ts — do not edit by hand.\n// The default theme library, embedded so a compiled binary is self-contained.\n`;
writeFileSync(OUT, `${header}export const EMBEDDED_THEMES: Record<string, any> = {\n${entries.join("\n")}\n};\n`);
console.log(`embedded ${entries.length} themes → src/embedded-themes.gen.ts`);
