#!/usr/bin/env bun
// Codegen: emit a static target manifest so a `bun build --compile` binary has
// its targets without readdir-ing src/targets/ at runtime (that dir doesn't
// exist next to a standalone binary). Dev still uses live auto-discovery; this
// is only the binary fallback. Regenerate when you add/remove a target:
//   bun scripts/embed-targets.ts   (run automatically by build:binary)
import { readdirSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

const REPO = resolve(dirname(new URL(import.meta.url).pathname), "..");
const OUT = join(REPO, "src", "targets.gen.ts");

const files = readdirSync(join(REPO, "src", "targets"))
  .filter((f) => f.endsWith(".ts") && !f.startsWith("_"))
  .sort();

const imports = files.map((f, i) => `import t${i} from "./targets/${f.replace(/\.ts$/, ".ts")}";`).join("\n");
const list = files.map((_, i) => `t${i}`).join(", ");

writeFileSync(
  OUT,
  `// GENERATED by scripts/embed-targets.ts — do not edit by hand.\n` +
    `// Static target list for the compiled binary (dev uses live auto-discovery).\n` +
    `import type { Target } from "./target-kit.ts";\n${imports}\n\nexport const GEN_TARGETS: Target[] = [${list}];\n`,
);
console.log(`embedded ${files.length} targets → src/targets.gen.ts`);
