#!/usr/bin/env bun
// Codegen: merge two open-source catalogs into one font catalog module, so we
// reuse their curation instead of hand-maintaining a list:
//   - vendor/font-catalogs/programmingfonts.json  (braver/programmingfonts):
//       curated list + metadata — name, ligatures, license, zerostyle, website
//   - vendor/font-catalogs/nerd-fonts.json        (ryanoasis/nerd-fonts):
//       Nerd Font family string (imagePreviewFont), Homebrew cask (caskName),
//       release asset (folderName → <folderName>.tar.xz)
// Join by normalized name; NF data enriches where matched. Refresh the vendored
// JSONs with `bun run fonts:update`, then re-run this. Output is committed so
// `bun src/cli.ts` works with no build step.
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

const REPO = resolve(dirname(new URL(import.meta.url).pathname), "..");
const V = join(REPO, "vendor", "font-catalogs");
const OUT = join(REPO, "src", "fonts-catalog.gen.ts");

const pf = JSON.parse(readFileSync(join(V, "programmingfonts.json"), "utf8")) as Record<string, any>;
const nf = (JSON.parse(readFileSync(join(V, "nerd-fonts.json"), "utf8")) as any).fonts as any[];

const norm = (s: string) => (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
const stripNF = (s: string) => s.replace(/\s*nerd font.*$/i, "");
// The real installed Nerd Font family is `<patchedName> Nerd Font` (e.g.
// "GeistMono Nerd Font"). imagePreviewFont is a truncated *display* string that
// sometimes abbreviates to "… NF" (e.g. "GeistMono NF"), which never matches the
// installed font → we'd fall back to a non-installed base name. Build it properly.
const nfFamily = (patched?: string, fallback?: string): string | undefined => {
  const p = (patched ?? "").trim();
  if (!p) return fallback;
  return /nerd font$/i.test(p) ? p : `${p} Nerd Font`;
};

// index nerd-fonts by every name we might match on
const nfIndex = new Map<string, any>();
for (const f of nf) {
  for (const key of [f.unpatchedName, f.patchedName, stripNF(f.imagePreviewFont), f.folderName]) {
    if (key) nfIndex.set(norm(key), f);
  }
}

interface Entry {
  id: string;
  name: string;
  ligatures: boolean;
  mono: boolean;
  license?: string;
  zerostyle?: string;
  website?: string;
  nerdFont?: string; // family string to set for the patched build
  cask?: string; // homebrew cask id (NF variant)
  nfAsset?: string; // nerd-fonts release asset base (folderName) → <folderName>.tar.xz
}

const entries: Entry[] = [];
const usedNf = new Set<string>();
const usedIds = new Set<string>();
const uniqueId = (want: string): string => {
  let id = want || "font";
  for (let n = 2; usedIds.has(id); n++) id = `${want}-${n}`;
  usedIds.add(id);
  return id;
};

for (const [alias, p] of Object.entries(pf)) {
  const match = nfIndex.get(norm(p.name)) ?? nfIndex.get(norm(alias));
  if (match) usedNf.add(match.folderName);
  entries.push({
    id: uniqueId(alias),
    name: p.name,
    ligatures: !!p.ligatures,
    mono: true, // programmingfonts entries are all monospaced-for-programming
    license: p.license,
    zerostyle: p.zerostyle,
    website: p.website,
    ...(match
      ? { nerdFont: nfFamily(match.patchedName, match.imagePreviewFont), cask: `font-${match.caskName}-nerd-font`, nfAsset: match.folderName }
      : {}),
  });
}

// include Nerd-Font-only fonts that programmingfonts doesn't list
for (const f of nf) {
  if (usedNf.has(f.folderName)) continue;
  entries.push({
    id: uniqueId(norm(f.unpatchedName)),
    name: f.unpatchedName,
    ligatures: false,
    mono: f.isMonospaced !== false,
    license: f.licenseId,
    nerdFont: nfFamily(f.patchedName, f.imagePreviewFont),
    cask: `font-${f.caskName}-nerd-font`,
    nfAsset: f.folderName,
  });
}

entries.sort((a, b) => a.name.localeCompare(b.name));

const header =
  `// GENERATED by scripts/gen-font-catalog.ts — do not edit by hand.\n` +
  `// Merged from programmingfonts (metadata) + nerd-fonts (NF variant + install).\n` +
  `// ${entries.length} fonts, ${entries.filter((e) => e.nerdFont).length} with a Nerd Font variant.\n`;
writeFileSync(OUT, `${header}export interface CatalogEntry {\n  id: string; name: string; ligatures: boolean; mono: boolean;\n  license?: string; zerostyle?: string; website?: string;\n  nerdFont?: string; cask?: string; nfAsset?: string;\n}\nexport const CATALOG: CatalogEntry[] = ${JSON.stringify(entries, null, 0)};\n`);
console.log(`generated ${entries.length} fonts (${entries.filter((e) => e.nerdFont).length} with Nerd Font) → src/fonts-catalog.gen.ts`);
